- name: Create the 1password CLI directory
  file:
    state: directory
    dest: "{{ ansible_env.HOME }}/.op"
    mode: 0700
    owner: "{{ ansible_user_id }}"

- name: Check if there's a 1password cli update
  command: /usr/local/bin/op update
  register: R_op_update
  changed_when:
    - ("Please download our latest version" in R_op_update.stdout)
  tags:
    - post
    - internet
    - onepassword

- name: Update 1password CLI
  command: brew cask reinstall 1password-cli
  when:
    - ("Please download our latest version" in R_op_update.stdout)
  tags:
    - post
    - internet
    - onepassword
