- name: Make sure zsh directory exists
  file:
    state: directory
    dest: "{{ role_path }}/zsh"
    mode: 0700
    owner: "{{ ansible_user_id }}"

- name: Template env.zsh into zsh/env.zsh
  template:
    src: env.zsh.j2
    dest: "{{ role_path }}/zsh/env.zsh"
    mode: 0600
    owner: "{{ ansible_user_id }}"
