- name: Make sure the config directory exists
  file:
    state: directory
    dest: "{{ ansible_env.HOME }}/.config"
    mode: 0700
    owner: "{{ ansible_user_id }}"

- name: Get the value of our hub personal access token
  set_fact:
    hub_pat: "{{
      lookup(
        'onepassword_raw',
        'Github',
        subdomain=op_auths['me'].shorthand,
        username=op_auths['me'].email,
        secret_key=op_auths['me'].secret_key,
        vault_password=lookup('vars', 'op_password_'+op_auths['me'].shorthand)
      ) | json_query('details.sections[?title==`Personal Access Tokens`].fields | [] | [?t==`PAT - hub`].v | [0]')
    }}"
  no_log: true
  tags:
    - post
    - 1password

- name: Write the hub config file
  template:
    src: hub.j2
    dest: "{{ ansible_env.HOME }}/.config/hub"
    mode: 0600
    owner: "{{ ansible_user_id }}"
  no_log: true
  tags:
    - post
    - 1password
