- name: Make the wrangler directory
  file:
    state: directory
    path: "{{ ansible_env.HOME }}/.wrangler"
    mode: 0700
    owner: "{{ ansible_user_id }}"
  register: R_wrangler_dir

- name: Make the wrangler config directory
  file:
    state: directory
    path: "{{ R_wrangler_dir.path }}/config"
    mode: 0700
    owner: "{{ ansible_user_id }}"
  register: R_wrangler_config_dir

- name: Get our cloudflare account ID
  set_fact:
    cloudflare_account_id: "{{
      lookup(
        'onepassword_raw',
        'Cloudflare'
      ) | json_query('details.sections[?title==`API Tokens`].fields | [] | [?t==`Account ID`].v | [0]')
    }}"
  no_log: true
  tags:
    - post
    - onepassword

- name: Get our wrangler api token
  set_fact:
    wrangler_api_token: "{{
      lookup(
        'onepassword_raw',
        'Cloudflare'
      ) | json_query('details.sections[?title==`API Tokens`].fields | [] | [?t==`wrangler-local`].v | [0]')
    }}"
  no_log: true
  tags:
    - post
    - onepassword

- name: Write the wrangler config file
  template:
    src: default.toml
    dest: "{{ R_wrangler_config_dir.path }}/default.toml"
    mode: 0600
    owner: "{{ ansible_user_id }}"
  tags:
    - post
    - onepassword
