# https://starship.rs/config/

# Integrations are off by default unless they are added to this format string
# Default: https://starship.rs/config/#default-prompt-format
format = """
$username\
$hostname\
$localip\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$jobs\
$battery\
$time\
$line_break\
$character
"""

# Print a new line at the start of the prompt
add_newline = true

# abort commands that take longer than 100ms
command_timeout = 300

[cmd_duration]
min_time = 300
show_milliseconds = true
format = "[$duration]($style)"

[directory]
truncate_to_repo = false
truncation_length = 10
truncation_symbol = ".../"

[git_branch]
symbol = ""
