- name: Setup
  hosts: all
  connection: local
  roles:
    - homebrew
    - 1password
    - ansible
    - aws-vault
    - bat
    - bd
    - bin
    - docker
    - editor
    - fonts
    - fzf
    - git
    - go
    - goreleaser
    - htop
    - hyper
    - mac
    - node
    - prettyping
    - projects
    - python
    - ssh
    - terraform
    - tldr
    - transmission
    - zsh
