- name: Setup
  hosts: all
  connection: local
  roles:
    - { role: homebrew,     tags: ['homebrew']     }
    - { role: 1password,    tags: ['1password']    }
    - { role: alacritty,    tags: ['alacritty']    }
    - { role: ansible,      tags: ['ansible']      }
    - { role: aws,          tags: ['aws']          }
    - { role: bat,          tags: ['bat']          }
    - { role: bin,          tags: ['bin']          }
    - { role: certs,        tags: ['certs']        }
    - { role: docker,       tags: ['docker']       }
    - { role: editor,       tags: ['editor']       }
    - { role: fonts,        tags: ['fonts']        }
    - { role: git,          tags: ['git']          }
    - { role: go,           tags: ['go']           }
    - { role: goreleaser,   tags: ['goreleaser']   }
    - { role: hub,          tags: ['hub']          }
    - { role: mac,          tags: ['mac']          }
    - { role: netrc,        tags: ['netrc']        }
    - { role: node,         tags: ['node']         }
    - { role: pgp,          tags: ['pgp']          }
    - { role: projects,     tags: ['projects']     }
    - { role: python,       tags: ['python']       }
    - { role: ssh,          tags: ['ssh']          }
    - { role: starship,     tags: ['starship']     }
    - { role: terraform,    tags: ['terraform']    }
    - { role: transmission, tags: ['transmission'] }
    - { role: zsh,          tags: ['zsh']          }
