git_users:
  personal:
    shorthand: me
    name: Sean Lingren
    email: sean@lingrino.com
    signing_key: 7B9F176F
  work:
    shorthand: work
    name: Sean Lingren
    email: lingrino@github.com
    signing_key: 7226342E
    path: ~/projects/work/
