brew_prefix: /usr/local

host_taps:
  - loomhq/tap
  - versent/homebrew-taps

host_brews:
  - aws-iam-authenticator
  - dog
  - hadolint
  - loomhq/tap/loomctl
  - minikube
  - packer
  - versent/homebrew-taps/saml2aws
  - shellcheck
  - terragrunt
  - vault
