# run `brew --prefix` to show
brew_prefix: /opt/homebrew

taps:
  - clementtsang/bottom
  - cloudflare/cloudflare
  - golangci/tap
  - goreleaser/tap
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-versions
  - lingrino/tap

brews:
  - ansible
  - ansible-lint
  - awscli
  # - bandwhich
  - bat
  - clementtsang/bottom/bottom
  - cloudflare/cloudflare/cloudflared
  - coreutils
  - ctop
  - dive
  - doctl
  # - dog
  - dust
  - exa
  - fd
  - fzf
  - git
  - git-delta
  - git-lfs
  - gh
  - go
  - golangci/tap/golangci-lint
  - goreleaser/tap/goreleaser
  # - hadolint
  - helm
  - hyperfine
  - jq
  # - kubernetes-cli
  - less
  - libgit2
  - lingrino/tap/cami
  - lingrino/tap/glen
  - lingrino/tap/vaku
  - markdownlint-cli
  - mas
  - nmap
  - node
  - openssl
  # - packer
  - prettyping
  - procs
  - python
  - rbenv
  - readline
  - ripgrep
  - ruby-build
  - rustup-init
  - scc
  - sd
  - serverless
  # - shellcheck
  - shfmt
  - starship
  # - terraform
  - tflint
  # - vault
  - watch
  - wget
  - yq
  - zoxide
  - zsh

casks:
  - 1password
  - 1password-cli
  - alfred
  - aws-vault
  - cleanshot
  - cloudflare-warp
  # - docker
  - fantastical
  - google-chrome
  - gpg-suite
  - istat-menus
  - iterm2-beta
  - logitech-options
  - loom
  - notion
  - slack
  - spotify
  - visual-studio-code
  - vlc
  - yubico-yubikey-manager
  - zoom
  - zsa-wally

apps:
  - id: 1107421413
    name: 1Blocker
  - id: 1481302432
    name: Instapaper Save
  - id: 441258766
    name: Magnets
  - id: 1529448980
    name: Reeder
  - id: 1376402589
    name: StopTheMadness
  - id: 904280696
    name: Things
