# run `brew --prefix` to show
brew_prefix: /usr/local

taps:
  - clementtsang/bottom
  - golangci/tap
  - goreleaser/tap
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-versions
  - lingrino/tap

brews:
  - ansible
  - ansible-lint
  - awscli
  - bandwhich
  - bat
  - clementtsang/bottom/bottom
  - coreutils
  - ctop
  - dive
  - doctl
  - dog
  - dust
  - exa
  - fd
  - fzf
  - git
  - git-delta
  - git-lfs
  - gh
  - go
  - golangci/tap/golangci-lint
  - goreleaser/tap/goreleaser
  - hadolint
  - hyperfine
  - jq
  - kubernetes-cli
  - less
  - libgit2
  - lingrino/tap/cami
  - lingrino/tap/glen
  - lingrino/tap/vaku
  - markdownlint-cli
  - mas
  - nmap
  - node
  - openssl
  - packer
  - prettyping
  - procs
  - python
  - rbenv
  - readline
  - ripgrep
  - ruby-build
  - rustup-init
  - scc
  - sd
  - serverless
  - shellcheck
  - shfmt
  - starship
  - terraform
  - tflint
  - unrar
  - vault
  - watch
  - wget
  - zoxide
  - zsh

casks:
  - 1password
  - 1password-cli
  - adguard
  - alfred
  - aws-vault
  - cleanshot
  - cloudflare-warp
  - docker
  - dropbox
  - fantastical
  - google-chrome
  - gpg-suite
  - istat-menus
  - iterm2-beta
  - java
  - logitech-options
  - slack
  - spotify
  - visual-studio-code
  - vlc
  - yubico-yubikey-manager
  - zoom
  - zsa-wally

apps:
  - id: 1091189122
    name: Bear
  - id: 1487937127
    name: Craft
  - id: 441258766
    name: Magnet
  - id: 1475387142
    name: Tailscale
  - id: 904280696
    name: Things3
