- name: Create the ssh directory
  file:
    state: directory
    path: "{{ ansible_env.HOME }}/.ssh"
    mode: 0700
    owner: "{{ ansible_user_id }}"
  register: R_ssh_dir

- name: Copy over the ssh config file
  copy:
    src: config
    dest: "{{ R_ssh_dir.path }}/config"
    mode: 0600
    owner: "{{ ansible_user_id }}"

# Can't use the 1password module here beacuse it
# doesn't support getting note content
# https://docs.ansible.com/ansible/devel/plugins/lookup/onepassword.html
####################
### Personal     ###
####################
- name: Get my private key from 1password
  command: /usr/local/bin/op get item {{ op_privkey_uuid }}
  no_log: true
  environment:
    OP_SESSION_my: "{{ R_op_signin.stdout }}"
  register: R_privkey
  changed_when:
    - R_privkey.rc != 0
  tags:
    - post
    - 1password

- name: Copy my private key to personal
  copy:
    content: "{{ R_privkey.stdout | from_json | json_query('details.notesPlain') }}"
    dest: "{{ ansible_env.HOME }}/.ssh/personal"
    mode: 0600
    owner: "{{ ansible_user_id }}"
  no_log: true
  tags:
    - post
    - 1password

- name: Get my public key from 1password
  command: /usr/local/bin/op get item {{ op_pubkey_uuid }}
  no_log: true
  environment:
    OP_SESSION_my: "{{ R_op_signin.stdout }}"
  register: R_pubkey
  changed_when:
    - R_pubkey.rc != 0
  tags:
    - post
    - 1password

- name: Copy my public key to personal.pub
  copy:
    content: "{{ R_pubkey.stdout | from_json | json_query('details.notesPlain') }}"
    dest: "{{ ansible_env.HOME }}/.ssh/personal.pub"
    mode: 0600
    owner: "{{ ansible_user_id }}"
  no_log: true
  tags:
    - post
    - 1password

####################
### Work         ###
####################
- name: Get my work private key from 1password
  command: /usr/local/bin/op get item {{ op_privkey_work_uuid }}
  no_log: true
  environment:
    OP_SESSION_my: "{{ R_op_signin.stdout }}"
  register: R_privkey_work
  changed_when:
    - R_privkey_work.rc != 0
  tags:
    - post
    - 1password

- name: Copy my private key to work
  copy:
    content: "{{ R_privkey_work.stdout | from_json | json_query('details.notesPlain') }}"
    dest: "{{ ansible_env.HOME }}/.ssh/work"
    mode: 0600
    owner: "{{ ansible_user_id }}"
  no_log: true
  tags:
    - post
    - 1password

- name: Get my work public key from 1password
  command: /usr/local/bin/op get item {{ op_pubkey_work_uuid }}
  no_log: true
  environment:
    OP_SESSION_my: "{{ R_op_signin.stdout }}"
  register: R_pubkey_work
  changed_when:
    - R_pubkey_work.rc != 0
  tags:
    - post
    - 1password

- name: Copy my public key to work.pub
  copy:
    content: "{{ R_pubkey_work.stdout | from_json | json_query('details.notesPlain') }}"
    dest: "{{ ansible_env.HOME }}/.ssh/work.pub"
    mode: 0600
    owner: "{{ ansible_user_id }}"
  no_log: true
  tags:
    - post
    - 1password
