# https://www.nordtheme.com/docs/ports/dircolors/installation
- name: Write the nord dircolors file
  get_url:
    url: https://raw.githubusercontent.com/arcticicestudio/nord-dircolors/HEAD/src/dir_colors
    dest: "{{ ansible_env.HOME }}/.dir_colors"
    mode: 0600
    owner: "{{ ansible_user_id }}"
  tags:
    - internet

- name: Create the zsh directories
  file:
    state: directory
    path: "{{ item }}"
    mode: 0755
    owner: "{{ ansible_user_id }}"
  loop:
    - "{{ brew_prefix }}/share/zsh"
    - "{{ brew_prefix }}/share/zsh/site-functions"

- name: Clone zsh-completions into our zsh directory
  git:
    repo: https://github.com/zsh-users/zsh-completions.git
    dest: "{{ brew_prefix }}/share/zsh/completions"
    clone: true
    depth: 1
    update: true
    version: HEAD
  tags:
    - internet

- name: Clone zsh-autosuggestions into our zsh directory
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ brew_prefix }}/share/zsh/autosuggestions"
    clone: true
    depth: 1
    update: true
    version: HEAD
  tags:
    - internet

- name: Clone zsh-syntax-highlighting into our zsh directory
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ brew_prefix }}/share/zsh/syntax-highlighting"
    clone: true
    depth: 1
    update: true
    version: HEAD
  tags:
    - internet

- name: Write the zsh rc file
  template:
    src: zshrc.zsh.j2
    dest: "{{ ansible_env.HOME }}/.zshrc"
    mode: 0700
    owner: "{{ ansible_user_id }}"

- name: Write /etc/shells
  template:
    src: shells.j2
    dest: /etc/shells
    mode: 0644
  become: true
  become_user: root
  tags:
    - sudo

- name: Use zsh as my default shell
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{ brew_prefix }}/bin/zsh"
  become: true
  become_user: root
  tags:
    - sudo
