- name: Get latest pure.zsh
  get_url:
    url: https://raw.githubusercontent.com/sindresorhus/pure/master/pure.zsh
    dest: "/usr/local/share/zsh/site-functions/prompt_pure_setup"
    mode: 0600
    owner: "{{ ansible_user_id }}"

- name: Get latest async.zsh
  get_url:
    url: https://raw.githubusercontent.com/sindresorhus/pure/master/async.zsh
    dest: "/usr/local/share/zsh/site-functions/async"
    mode: 0600
    owner: "{{ ansible_user_id }}"

- name: Write zsh rc file
  template:
    src: zshrc.zsh.j2
    dest: "{{ ansible_env.HOME }}/.zshrc"
    mode: 0700
    owner: "{{ ansible_user_id }}"

- name: Write /etc/shells
  copy:
    src: shells
    dest: /etc/shells
    mode: 644
  become: true
  become_user: root
  tags:
    - sudo

- name: Use zsh as my default shell
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/local/bin/zsh
  become: true
  become_user: root
  tags:
    - sudo
