# This is my own configuration for Alacritty. The project is still
# in beta so config may need to be updated regularly. I have removed
# all comments from the original file, but that file can be found
# here - https://github.com/jwilm/alacritty/blob/master/alacritty.yml

##########################
### Window             ###
##########################
dynamic_title:      true
background_opacity: 1.0

window:
  decorations:  buttonless
  startup_mode: Windowed

  padding:
    x: 2
    y: 5

  dimensions:
    columns: 0
    lines:   0

scrolling:
  history:         50000
  auto_scroll:     false
  multiplier:      3

##########################
### Text               ###
##########################
tabspaces:                         8
draw_bold_text_with_bright_colors: true

cursor:
  style:            Beam
  unfocused_hollow: true

font:
  size:             13.0
  use_thin_strokes: true

  normal:
    family: Hack
    style:  Regular
  bold:
    family: Hack
    style:  Bold
  italic:
    family: Hack
    style:  Italic

  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0

##########################
### Behavior           ###
##########################
working_directory:  None
live_config_reload: true

selection:
  save_to_clipboard:     true
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

##########################
### Mouse              ###
##########################
mouse:
  hide_when_typing: true

  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  url:
    modifiers: None

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

##########################
### Keyboard           ###
##########################
key_bindings:
  # My Custom Defaults

  # Open a new window
  - { key: N, mods: Command, action: SpawnNewInstance }

  # Open our settings
  - { key: Comma,  mods: Command, command:
      { program: "open", args: ["/Users/lingrino/projects/dotfiles/roles/alacritty/files/alacritty.yml"] } }

  # Reload zsh and reset
  - { key: R, mods: Command, chars: "reload\n" }

  # These two make command left/right replicat home/end
  # They work together with bindings in my keybindings.zsh
  - { key: Left,   mods: Command, chars: "\x1b[H" } # Beginning of line
  - { key: Right,  mods: Command, chars: "\x1b[F" } # End of line

  # Alacritty Mac Defaults (I have not changed)
  - { key: Key0,   mods: Command,         action: ResetFontSize    }
  - { key: Equals, mods: Command,         action: IncreaseFontSize }
  - { key: Add,    mods: Command,         action: IncreaseFontSize }
  - { key: Minus,  mods: Command,         action: DecreaseFontSize }
  - { key: K,      mods: Command,         action: ClearHistory     }
  - { key: K,      mods: Command,         chars: "\x0c"            }
  - { key: V,      mods: Command,         action: Paste            }
  - { key: C,      mods: Command,         action: Copy             }
  - { key: H,      mods: Command,         action: Hide             }
  - { key: Q,      mods: Command,         action: Quit             }
  - { key: W,      mods: Command,         action: Quit             }
  - { key: F,      mods: Command|Control, action: ToggleFullscreen }

  # Alacritty Defaults (I have not changed)
  - { key: Paste,                   action: Paste                            }
  - { key: Copy,                    action: Copy                             }
  - { key: L,        mods: Control, action: ClearLogNotice                   }
  - { key: L,        mods: Control, chars: "\x0c"                            }
  - { key: Home,     mods: Alt,     chars: "\x1b[1;3H"                       }
  - { key: Home,                    chars: "\x1bOH",        mode: AppCursor  }
  - { key: Home,                    chars: "\x1b[H",        mode: ~AppCursor }
  - { key: End,      mods: Alt,     chars: "\x1b[1;3F"                       }
  - { key: End,                     chars: "\x1bOF",        mode: AppCursor  }
  - { key: End,                     chars: "\x1b[F",        mode: ~AppCursor }
  - { key: PageUp,   mods: Shift,   action: ScrollPageUp,   mode: ~Alt       }
  - { key: PageUp,   mods: Shift,   chars: "\x1b[5;2~",     mode: Alt        }
  - { key: PageUp,   mods: Control, chars: "\x1b[5;5~"                       }
  - { key: PageUp,   mods: Alt,     chars: "\x1b[5;3~"                       }
  - { key: PageUp,                  chars: "\x1b[5~"                         }
  - { key: PageDown, mods: Shift,   action: ScrollPageDown, mode: ~Alt       }
  - { key: PageDown, mods: Shift,   chars: "\x1b[6;2~",     mode: Alt        }
  - { key: PageDown, mods: Control, chars: "\x1b[6;5~"                       }
  - { key: PageDown, mods: Alt,     chars: "\x1b[6;3~"                       }
  - { key: PageDown,                chars: "\x1b[6~"                         }
  - { key: Tab,      mods: Shift,   chars: "\x1b[Z"                          }
  - { key: Back,                    chars: "\x7f"                            }
  - { key: Back,     mods: Alt,     chars: "\x1b\x7f"                        }
  - { key: Insert,                  chars: "\x1b[2~"                         }
  - { key: Delete,                  chars: "\x1b[3~"                         }
  - { key: Left,     mods: Shift,   chars: "\x1b[1;2D"                       }
  - { key: Left,     mods: Control, chars: "\x1b[1;5D"                       }
  - { key: Left,     mods: Alt,     chars: "\x1b[1;3D"                       }
  - { key: Left,                    chars: "\x1b[D",        mode: ~AppCursor }
  - { key: Left,                    chars: "\x1bOD",        mode: AppCursor  }
  - { key: Right,    mods: Shift,   chars: "\x1b[1;2C"                       }
  - { key: Right,    mods: Control, chars: "\x1b[1;5C"                       }
  - { key: Right,    mods: Alt,     chars: "\x1b[1;3C"                       }
  - { key: Right,                   chars: "\x1b[C",        mode: ~AppCursor }
  - { key: Right,                   chars: "\x1bOC",        mode: AppCursor  }
  - { key: Up,       mods: Shift,   chars: "\x1b[1;2A"                       }
  - { key: Up,       mods: Control, chars: "\x1b[1;5A"                       }
  - { key: Up,       mods: Alt,     chars: "\x1b[1;3A"                       }
  - { key: Up,                      chars: "\x1b[A",        mode: ~AppCursor }
  - { key: Up,                      chars: "\x1bOA",        mode: AppCursor  }
  - { key: Down,     mods: Shift,   chars: "\x1b[1;2B"                       }
  - { key: Down,     mods: Control, chars: "\x1b[1;5B"                       }
  - { key: Down,     mods: Alt,     chars: "\x1b[1;3B"                       }
  - { key: Down,                    chars: "\x1b[B",        mode: ~AppCursor }
  - { key: Down,                    chars: "\x1bOB",        mode: AppCursor  }
  - { key: F1,                      chars: "\x1bOP"                          }
  - { key: F2,                      chars: "\x1bOQ"                          }
  - { key: F3,                      chars: "\x1bOR"                          }
  - { key: F4,                      chars: "\x1bOS"                          }
  - { key: F5,                      chars: "\x1b[15~"                        }
  - { key: F6,                      chars: "\x1b[17~"                        }
  - { key: F7,                      chars: "\x1b[18~"                        }
  - { key: F8,                      chars: "\x1b[19~"                        }
  - { key: F9,                      chars: "\x1b[20~"                        }
  - { key: F10,                     chars: "\x1b[21~"                        }
  - { key: F11,                     chars: "\x1b[23~"                        }
  - { key: F12,                     chars: "\x1b[24~"                        }
  - { key: F1,       mods: Shift,   chars: "\x1b[1;2P"                       }
  - { key: F2,       mods: Shift,   chars: "\x1b[1;2Q"                       }
  - { key: F3,       mods: Shift,   chars: "\x1b[1;2R"                       }
  - { key: F4,       mods: Shift,   chars: "\x1b[1;2S"                       }
  - { key: F5,       mods: Shift,   chars: "\x1b[15;2~"                      }
  - { key: F6,       mods: Shift,   chars: "\x1b[17;2~"                      }
  - { key: F7,       mods: Shift,   chars: "\x1b[18;2~"                      }
  - { key: F8,       mods: Shift,   chars: "\x1b[19;2~"                      }
  - { key: F9,       mods: Shift,   chars: "\x1b[20;2~"                      }
  - { key: F10,      mods: Shift,   chars: "\x1b[21;2~"                      }
  - { key: F11,      mods: Shift,   chars: "\x1b[23;2~"                      }
  - { key: F12,      mods: Shift,   chars: "\x1b[24;2~"                      }
  - { key: F1,       mods: Control, chars: "\x1b[1;5P"                       }
  - { key: F2,       mods: Control, chars: "\x1b[1;5Q"                       }
  - { key: F3,       mods: Control, chars: "\x1b[1;5R"                       }
  - { key: F4,       mods: Control, chars: "\x1b[1;5S"                       }
  - { key: F5,       mods: Control, chars: "\x1b[15;5~"                      }
  - { key: F6,       mods: Control, chars: "\x1b[17;5~"                      }
  - { key: F7,       mods: Control, chars: "\x1b[18;5~"                      }
  - { key: F8,       mods: Control, chars: "\x1b[19;5~"                      }
  - { key: F9,       mods: Control, chars: "\x1b[20;5~"                      }
  - { key: F10,      mods: Control, chars: "\x1b[21;5~"                      }
  - { key: F11,      mods: Control, chars: "\x1b[23;5~"                      }
  - { key: F12,      mods: Control, chars: "\x1b[24;5~"                      }
  - { key: F1,       mods: Alt,     chars: "\x1b[1;6P"                       }
  - { key: F2,       mods: Alt,     chars: "\x1b[1;6Q"                       }
  - { key: F3,       mods: Alt,     chars: "\x1b[1;6R"                       }
  - { key: F4,       mods: Alt,     chars: "\x1b[1;6S"                       }
  - { key: F5,       mods: Alt,     chars: "\x1b[15;6~"                      }
  - { key: F6,       mods: Alt,     chars: "\x1b[17;6~"                      }
  - { key: F7,       mods: Alt,     chars: "\x1b[18;6~"                      }
  - { key: F8,       mods: Alt,     chars: "\x1b[19;6~"                      }
  - { key: F9,       mods: Alt,     chars: "\x1b[20;6~"                      }
  - { key: F10,      mods: Alt,     chars: "\x1b[21;6~"                      }
  - { key: F11,      mods: Alt,     chars: "\x1b[23;6~"                      }
  - { key: F12,      mods: Alt,     chars: "\x1b[24;6~"                      }
  - { key: F1,       mods: Super,   chars: "\x1b[1;3P"                       }
  - { key: F2,       mods: Super,   chars: "\x1b[1;3Q"                       }
  - { key: F3,       mods: Super,   chars: "\x1b[1;3R"                       }
  - { key: F4,       mods: Super,   chars: "\x1b[1;3S"                       }
  - { key: F5,       mods: Super,   chars: "\x1b[15;3~"                      }
  - { key: F6,       mods: Super,   chars: "\x1b[17;3~"                      }
  - { key: F7,       mods: Super,   chars: "\x1b[18;3~"                      }
  - { key: F8,       mods: Super,   chars: "\x1b[19;3~"                      }
  - { key: F9,       mods: Super,   chars: "\x1b[20;3~"                      }
  - { key: F10,      mods: Super,   chars: "\x1b[21;3~"                      }
  - { key: F11,      mods: Super,   chars: "\x1b[23;3~"                      }
  - { key: F12,      mods: Super,   chars: "\x1b[24;3~"                      }
  - { key: NumpadEnter,             chars: "\n"                              }

##########################
### Color              ###
##########################
# Predefined Color Schemes
# https://github.com/jwilm/alacritty/wiki/Color-schemes

schemes:
  # https://github.com/pwaleczek/Argonaut-theme
  argonaut: &argonaut
    primary:
      background: '0x292C3E'
      foreground: '0xEBEBEB'
    cursor:
      text:   '0xFF261E'
      cursor: '0xFF261E'
    normal:
      black:   '0x0d0d0d'
      red:     '0xFF301B'
      green:   '0xA0E521'
      yellow:  '0xFFC620'
      blue:    '0x1BA6FA'
      magenta: '0x8763B8'
      cyan:    '0x21DEEF'
      white:   '0xEBEBEB'
    bright:
      black:   '0x6D7070'
      red:     '0xFF4352'
      green:   '0xB8E466'
      yellow:  '0xFFD750'
      blue:    '0x1BA6FA'
      magenta: '0xA578EA'
      cyan:    '0x73FBF1'
      white:   '0xFEFEF8'

  # https://draculatheme.com
  dracula: &dracula
    primary:
      background: '0x282a36'
      foreground: '0xf8f8f2'
    normal:
      black:   '0x000000'
      red:     '0xff5555'
      green:   '0x50fa7b'
      yellow:  '0xf1fa8c'
      blue:    '0xcaa9fa'
      magenta: '0xff79c6'
      cyan:    '0x8be9fd'
      white:   '0xbfbfbf'
    bright:
      black:   '0x575b70'
      red:     '0xff6e67'
      green:   '0x5af78e'
      yellow:  '0xf4f99d'
      blue:    '0xcaa9fa'
      magenta: '0xff92d0'
      cyan:    '0x9aedfe'
      white:   '0xe6e6e6'

  # https://github.com/cocopon/iceberg.vim
  iceberg: &iceberg
    primary:
      background: '0x161821'
      foreground: '0xd2d4de'
    normal:
      black:   '0x161821'
      red:     '0xe27878'
      green:   '0xb4be82'
      yellow:  '0xe2a478'
      blue:    '0x84a0c6'
      magenta: '0xa093c7'
      cyan:    '0x89b8c2'
      white:   '0xc6c8d1'
    bright:
      black:   '0x6b7089'
      red:     '0xe98989'
      green:   '0xc0ca8e'
      yellow:  '0xe9b189'
      blue:    '0x91acd1'
      magenta: '0xada0d3'
      cyan:    '0x95c4ce'
      white:   '0xd2d4de'

  # https://monokai.pro
  monokai-pro: &monokai-pro
    primary:
      background: '0x2D2A2E'
      foreground: '0xFCFCFA'
    normal:
      black:   '0x403E41'
      red:     '0xFF6188'
      green:   '0xA9DC76'
      yellow:  '0xFFD866'
      blue:    '0xFC9867'
      magenta: '0xAB9DF2'
      cyan:    '0x78DCE8'
      white:   '0xFCFCFA'
    bright:
      black:   '0x727072'
      red:     '0xFF6188'
      green:   '0xA9DC76'
      yellow:  '0xFFD866'
      blue:    '0xFC9867'
      magenta: '0xAB9DF2'
      cyan:    '0x78DCE8'
      white:   '0xFCFCFA'

  # https://github.com/taniarascia/new-moon
  new-moon: &new-moon
    primary:
      background: '0x2D2D2D'
      foreground: '0xB3B9C5'
    normal:
      black:   '0x2D2D2D'
      red:     '0xF2777A'
      green:   '0x92D192'
      yellow:  '0xFFD479'
      blue:    '0x6AB0F3'
      magenta: '0xE1A6F2'
      cyan:    '0x76D4D6'
      white:   '0xB3B9C5'
    bright:
      black:   '0x777C85'
      red:     '0xF2777A'
      green:   '0x76D4D6'
      yellow:  '0xFFEEA6'
      blue:    '0x6AB0F3'
      magenta: '0xE1A6F2'
      cyan:    '0x76D4D6'
      white:   '0xFFFFFF'

  # https://github.com/arcticicestudio/nord
  nord: &nord
    primary:
      background: '0x2E3440'
      foreground: '0xD8DEE9'
    normal:
      black:   '0x3B4252'
      red:     '0xBF616A'
      green:   '0xA3BE8C'
      yellow:  '0xEBCB8B'
      blue:    '0x81A1C1'
      magenta: '0xB48EAD'
      cyan:    '0x88C0D0'
      white:   '0xE5E9F0'
    bright:
      black:   '0x4C566A'
      red:     '0xBF616A'
      green:   '0xA3BE8C'
      yellow:  '0xEBCB8B'
      blue:    '0x81A1C1'
      magenta: '0xB48EAD'
      cyan:    '0x8FBCBB'
      white:   '0xECEFF4'

  # https://github.com/voronianski/oceanic-next-color-scheme
  oceanic-next: &oceanic-next
    primary:
      background: '0x1b2b34'
      foreground: '0xd8dee9'
    cursor:
      text: '0x1b2b34'
      cursor: '0xffffff'
    normal:
      black:   '0x343d46'
      red:     '0xEC5f67'
      green:   '0x99C794'
      yellow:  '0xFAC863'
      blue:    '0x6699cc'
      magenta: '0xc594c5'
      cyan:    '0x5fb3b3'
      white:   '0xd8dee9'
    bright:
      black:   '0x343d46'
      red:     '0xEC5f67'
      green:   '0x99C794'
      yellow:  '0xFAC863'
      blue:    '0x6699cc'
      magenta: '0xc594c5'
      cyan:    '0x5fb3b3'
      white:   '0xd8dee9'

  # https://github.com/sindresorhus/hyper-snazzy
  snazzy: &snazzy
    primary:
      background: '0x282a36'
      foreground: '0xeff0eb'
    normal:
      black:   '0x282a36'
      red:     '0xff5c57'
      green:   '0x5af78e'
      yellow:  '0xf3f99d'
      blue:    '0x57c7ff'
      magenta: '0xff6ac1'
      cyan:    '0x9aedfe'
      white:   '0xf1f1f0'
    bright:
      black:   '0x686868'
      red:     '0xff5c57'
      green:   '0x5af78e'
      yellow:  '0xf3f99d'
      blue:    '0x57c7ff'
      magenta: '0xff6ac1'
      cyan:    '0x9aedfe'
      white:   '0xf1f1f0'

  # https://ethanschoonover.com/solarized/
  solarized-dark: &solarized-dark
    primary:
      background: '0x002b36'
      foreground: '0x839496'
    cursor:
      text:   '0x002b36'
      cursor: '0x839496'
    normal:
      black:   '0x073642'
      red:     '0xdc322f'
      green:   '0x859900'
      yellow:  '0xb58900'
      blue:    '0x268bd2'
      magenta: '0xd33682'
      cyan:    '0x2aa198'
      white:   '0xeee8d5'
    bright:
      black:   '0x002b36'
      red:     '0xcb4b16'
      green:   '0x586e75'
      yellow:  '0x657b83'
      blue:    '0x839496'
      magenta: '0x6c71c4'
      cyan:    '0x93a1a1'
      white:   '0xfdf6e3'

  # https://github.com/huyvohcmc/tender-alacritty
  tender: &tender
    primary:
      background: '0x282828'
      foreground: '0xeeeeee'
    normal:
      black:   '0x282828'
      red:     '0xf43753'
      green:   '0xc9d05c'
      yellow:  '0xffc24b'
      blue:    '0xb3deef'
      magenta: '0xd3b987'
      cyan:    '0x73cef4'
      white:   '0xeeeeee'
    bright:
      black:   '0x4c4c4c'
      red:     '0xf43753'
      green:   '0xc9d05c'
      yellow:  '0xffc24b'
      blue:    '0xb3deef'
      magenta: '0xd3b987'
      cyan:    '0x73cef4'
      white:   '0xfeffff'

# This points to one of the schemes defined above. The 'colors'
# option must appear below the defined schemes
colors: *nord

##########################
### Unused             ###
##########################
alt_send_esc: true

enable_experimental_conpty_backend: false

visual_bell:
  duration: 0

debug:
  ref_test:           false
  log_level:          Warn
  render_timer:       false
  print_events:       false
  persistent_logging: false
