- name: Make sure the config directory exists
  file:
    state: directory
    dest: "{{ ansible_env.HOME }}/.config"
    mode: 0700
    owner: "{{ ansible_user_id }}"

- name: Create the goreleaser directory
  file:
    state: directory
    dest: "{{ ansible_env.HOME }}/.config/goreleaser"
    mode: 0700
    owner: "{{ ansible_user_id }}"

- name: Add the goreleaser github token file
  copy:
    content: "{{
      lookup(
        'onepassword_raw',
        'Github'
      ) | json_query('details.sections[?title==`Personal Access Tokens`].fields | [] | [?t==`PAT - goreleaser`].v | [0]')
    }}"
    dest: "{{ ansible_env.HOME }}/.config/goreleaser/github_token"
    mode: 0600
    owner: "{{ ansible_user_id }}"
  no_log: false # TODO
  tags:
    - post
    - onepassword
