- name: Make sure the config directory exists
  file:
    state: directory
    dest: "{{ ansible_env.HOME }}/.config"
    mode: 0700
    owner: "{{ ansible_user_id }}"

- name: Create the goreleaser directory
  file:
    state: directory
    dest: "{{ ansible_env.HOME }}/.config/goreleaser"
    mode: 0700
    owner: "{{ ansible_user_id }}"

- name: Add the goreleaser github token file
  copy:
    content: "{{
      lookup(
        'onepassword_raw',
        'Github',
        subdomain=op_auths['me'].shorthand,
        username=op_auths['me'].email,
        secret_key=op_auths['me'].secret_key,
        vault_password=lookup('vars', 'op_password_'+op_auths['me'].shorthand)
      ) | json_query('details.sections[?title==`Personal Access Tokens`].fields | [] | [?t==`PAT - goreleaser`].v | [0]')
    }}"
    dest: "{{ ansible_env.HOME }}/.config/goreleaser/github_token"
    mode: 0600
    owner: "{{ ansible_user_id }}"
  tags:
    - post
    - 1password
