- name: Store complete downloads in ~/Downloads
  osx_defaults:
    state: present
    domain: org.m0k.transmission
    key: DownloadFolder
    type: string
    value: "{{ ansible_env.HOME }}/Downloads"

- name: Don't prompt for confirmation before downloading
  osx_defaults:
    state: present
    domain: org.m0k.transmission
    key: "{{ item }}"
    type: bool
    value: false
  loop:
    - DownloadAsk
    - MagnetOpenAsk

- name: Only confirm when downloading
  osx_defaults:
    state: present
    domain: org.m0k.transmission
    key: "{{ item }}"
    type: bool
    value: true
  loop:
    - CheckQuitDownloading
    - CheckRemoveDownloading

- name: Trash original torrent files
  osx_defaults:
    state: present
    domain: org.m0k.transmission
    key: DeleteOriginalTorrent
    type: bool
    value: true

- name: Hide the donate message
  osx_defaults:
    state: present
    domain: org.m0k.transmission
    key: WarningDonate
    type: bool
    value: false

- name: Hide the legal disclaimer
  osx_defaults:
    state: present
    domain: org.m0k.transmission
    key: WarningLegal
    type: bool
    value: false

- name: Randomize port on launch
  osx_defaults:
    state: present
    domain: org.m0k.transmission
    key: RandomPort
    type: bool
    value: true

- name: Enable the blocklist
  osx_defaults:
    state: present
    domain: org.m0k.transmission
    key: BlocklistNew
    type: bool
    value: true

- name: Use a good IP blocklist
  osx_defaults:
    state: present
    domain: org.m0k.transmission
    key: BlocklistURL
    type: string
    value: http://john.bitsurge.net/public/biglist.p2p.gz

- name: Autoupdate the blocklist
  osx_defaults:
    state: present
    domain: org.m0k.transmission
    key: BlocklistAutoUpdate
    type: bool
    value: true

- name: Don't play a download sound
  osx_defaults:
    state: present
    domain: org.m0k.transmission
    key: PlayDownloadSound
    type: bool
    value: false

- name: Require encryption
  osx_defaults:
    state: present
    domain: org.m0k.transmission
    key: EncryptionRequire
    type: bool
    value: true

- name: Include beta releases
  osx_defaults:
    state: present
    domain: org.m0k.transmission
    key: AutoUpdateBeta
    type: bool
    value: true
