- name: Create the aws directory
  file:
    state: directory
    dest: "{{ ansible_env.HOME }}/.aws"
    mode: 0700
    owner: "{{ ansible_user_id }}"

- name: Write the aws config file
  copy:
    src: config
    dest: "{{ ansible_env.HOME }}/.aws/config"
    mode: 0600
    owner: "{{ ansible_user_id }}"
