- name: Enable graphite appearance
  osx_defaults:
    state: present
    domain: NSGlobalDomain
    key: AppleAquaColorVariant
    type: int
    value: 6

- name: Enable the dark menubar and dock
  osx_defaults:
    state: present
    domain: NSGlobalDomain
    key: AppleInterfaceStyle
    type: string
    value: Dark

- name: Autohide dock and menubar
  osx_defaults:
    state: present
    domain: NSGlobalDomain
    key: _HIHideMenuBar
    type: bool
    value: true
