- name: Enable font smoothing
  block:
    - osx_defaults:
        state: present
        domain: NSGlobalDomain
        key: AppleFontSmoothing
        type: int
        value: 1

    - osx_defaults:
        state: present
        domain: NSGlobalDomain
        key: CGFontRenderingFontSmoothingDisabled
        type: bool
        value: false

- name: Turn off transparency
  osx_defaults:
    state: present
    domain: com.apple.universalaccess
    key: reduceTransparency
    type: bool
    value: true

- name: Set sidebar icon size to medium
  osx_defaults:
    state: present
    domain: NSGlobalDomain
    key: NSTableViewDefaultSizeMode
    type: int
    value: 2

- name: Always show scrollbars
  osx_defaults:
    state: present
    domain: NSGlobalDomain
    key: AppleShowScrollBars
    type: string
    value: "Always"

- name: Save to disk by default
  osx_defaults:
    state: present
    domain: NSGlobalDomain
    key: NSDocumentSaveNewDocumentsToCloud
    type: bool
    value: false

- name: Expand save panel by default
  osx_defaults:
    state: present
    domain: NSGlobalDomain
    key: "{{ item }}"
    type: bool
    value: true
  loop:
    - NSNavPanelExpandedStateForSaveMode
    - NSNavPanelExpandedStateForSaveMode2

- name: Expand print panel by default
  osx_defaults:
    state: present
    domain: NSGlobalDomain
    key: "{{ item }}"
    type: bool
    value: true
  loop:
    - PMPrintingExpandedStateForPrint
    - PMPrintingExpandedStateForPrint2

- name: Allow scroll-to-zoom when holding control
  osx_defaults:
    state: present
    domain: com.apple.universalaccess
    key: closeViewScrollWheelToggle
    type: bool
    value: true

- name: Allow scroll-to-zoom to use max zoom
  osx_defaults:
    state: present
    domain: com.apple.universalaccess
    key: HIDScrollZoomModifierMask
    type: int
    value: 262144

- name: Follow keyboard when using scroll-to-zoom
  osx_defaults:
    state: present
    domain: com.apple.universalaccess
    key: closeViewZoomFollowsFocus
    type: bool
    value: true

- name: Enable HiDPI display modes
  osx_defaults:
    state: present
    domain: /Library/Preferences/com.apple.windowserver
    key: DisplayResolutionEnabled
    type: bool
    value: true
  become: true
  become_user: root
  tags:
    - sudo

- name: Enable ctrl+option+cmd to drag windows
  osx_defaults:
    state: present
    domain: com.apple.universalaccess
    key: NSWindowShouldDragOnGesture
    type: string
    value: "YES"
