- name: Disable the desktop
  osx_defaults:
    state: present
    domain: com.apple.finder
    key: CreateDesktop
    type: bool
    value: false

- name: Allow quitting with cmd+Q
  osx_defaults:
    state: present
    domain: com.apple.finder
    key: QuitMenuItem
    type: bool
    value: true

- name: Set projects as the default location for new finder windows
  block:
  - name: Set the default location as a path
    osx_defaults:
      state: present
      domain: com.apple.finder
      key: NewWindowTarget
      type: string
      value: PfLo

  - name: Set the default location as a path
    osx_defaults:
      state: present
      domain: com.apple.finder
      key: NewWindowTargetPath
      type: string
      value: "file://{{ projects_folder_path | expanduser }}/"

- name: Disable finder animations
  osx_defaults:
    state: present
    domain: com.apple.finder
    key: DisableAllAnimations
    type: bool
    value: true

- name: Show all extensions in finder
  osx_defaults:
    state: present
    domain: com.apple.finder
    key: AppleShowAllExtensions
    type: bool
    value: true

- name: Show the status bar in finder
  osx_defaults:
    state: present
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true

- name: Display full path of item as finder window title
  osx_defaults:
    state: present
    domain: com.apple.finder
    key: _FXShowPosixPathInTitle
    type: bool
    value: true

- name: Sort folders before files
  osx_defaults:
    state: present
    domain: com.apple.finder
    key: _FXSortFoldersFirst
    type: bool
    value: true

- name: Search the current folder by default
  osx_defaults:
    state: present
    domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: SCcf

- name: Disable warning when changing a file extension
  osx_defaults:
    state: present
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false

- name: Use column view by default
  osx_defaults:
    state: present
    domain: com.apple.Finder
    key: FXPreferredViewStyle
    type: string
    value: clmv

- name: Disable empty trash warning
  osx_defaults:
    state: present
    domain: com.apple.Finder
    key: WarnOnEmptyTrash
    type: bool
    value: false

- name: Don't create .DS_Store on network or usb drives
  osx_defaults:
    state: present
    domain: com.apple.desktopservices
    key: "{{ item }}"
    type: bool
    value: true
  loop:
    - DSDontWriteUSBStores
    - DSDontWriteNetworkStores

- name: Don't show devices on desktop
  osx_defaults:
    state: present
    domain: com.apple.finder
    key: "{{ item }}"
    type: bool
    value: false
  loop:
    - ShowHardDrivesOnDesktop
    - ShowMountedServersOnDesktop
    - ShowRemovableMediaOnDesktop
    - ShowExternalHardDrivesOnDesktop

# Does not actually show 'changed' when the attribute changes
# not sure how to properly do the update and know when it has changed
- name: Show the users library folder
  command: chflags nohidden {{ ansible_env.HOME }}/Library
  register: R_library_nohidden
  changed_when:
    - (R_library_nohidden.stderr != "") or
      (R_library_nohidden.stdout != "")

# Does not actually show 'changed' when the attribute changes
# not sure how to properly do the update and know when it has changed
- name: Show the /Volumes folder
  command: chflags nohidden /Volumes
  become: true
  become_user: root
  register: R_volumes_nohidden
  changed_when:
    - (R_volumes_nohidden.stderr != "") or
      (R_volumes_nohidden.stdout != "")
  tags:
    - sudo