- name: Disable resume
  osx_defaults:
    state: present
    domain: com.apple.systempreferences
    key: NSQuitAlwaysKeepsWindows
    type: bool
    value: false

- name: Disable auto termination of inactive apps
  osx_defaults:
    state: present
    domain: NSGlobalDomain
    key: NSDisableAutomaticTermination
    type: bool
    value: true

- name: Ask for password after sleep/screensaver
  osx_defaults:
    state: present
    domain: com.apple.screensaver
    key: askForPassword
    type: int
    value: 1

- name: Require password immediately after sleep/screensaver
  osx_defaults:
    state: present
    domain: com.apple.screensaver
    key: askForPasswordDelay
    type: int
    value: 0
