# https://damieng.com/blog/2015/04/24/make-home-end-keys-behave-like-windows-on-mac-os-x
- name: Make sure the ~/Library/KeyBindings directory exists
  file:
    state: directory
    dest: "{{ ansible_env.HOME }}/Library/KeyBindings"
    mode: 0700
    owner: "{{ ansible_user_id }}"

- name: Copy over home/end keybindings
  copy:
    src: DefaultKeyBinding.dict
    dest: "{{ ansible_env.HOME }}/Library/KeyBindings/DefaultKeyBinding.dict"
    mode: 0600
    owner: "{{ ansible_user_id }}"

- name: Use press-and-hold to repeat key
  osx_defaults:
    state: present
    domain: NSGlobalDomain
    key: ApplePressAndHoldEnabled
    type: bool
    value: false

- name: Set a fast key repeat
  osx_defaults:
    state: present
    domain: NSGlobalDomain
    key: KeyRepeat
    type: int
    value: 2

- name: Set a fast initial key repeat
  osx_defaults:
    state: present
    domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: int
    value: 12

- name: Enable full keyboard access in all dialogs
  osx_defaults:
    state: present
    domain: NSGlobalDomain
    key: AppleKeyboardUIMode
    type: int
    value: 3

- name: Disable automatic capitalization
  osx_defaults:
    state: present
    domain: NSGlobalDomain
    key: NSAutomaticCapitalizationEnabled
    type: bool
    value: true

- name: Disable smart quotes
  osx_defaults:
    state: present
    domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: false

- name: Disable smart dashes
  osx_defaults:
    state: present
    domain: NSGlobalDomain
    key: NSAutomaticDashSubstitutionEnabled
    type: bool
    value: false

- name: Disable smart period substitution
  osx_defaults:
    state: present
    domain: NSGlobalDomain
    key: NSAutomaticPeriodSubstitutionEnabled
    type: bool
    value: false

- name: Disable autocorrect
  osx_defaults:
    state: present
    domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false
