# - name: Disable all spotlight indexes
#   osx_defaults:
#     state: present
#     domain: com.apple.spotlight
#     key: orderedItems
#     type: array
#     value:
#       - '{"enabled" = 0;"name" = "APPLICATIONS";}'
#       - '{"enabled" = 0;"name" = "SYSTEM_PREFS";}'
#       - '{"enabled" = 0;"name" = "DIRECTORIES";}'
#       - '{"enabled" = 0;"name" = "PDF";}'
#       - '{"enabled" = 0;"name" = "FONTS";}'
#       - '{"enabled" = 0;"name" = "DOCUMENTS";}'
#       - '{"enabled" = 0;"name" = "MESSAGES";}'
#       - '{"enabled" = 0;"name" = "CONTACT";}'
#       - '{"enabled" = 0;"name" = "EVENT_TODO";}'
#       - '{"enabled" = 0;"name" = "IMAGES";}'
#       - '{"enabled" = 0;"name" = "BOOKMARKS";}'
#       - '{"enabled" = 0;"name" = "MUSIC";}'
#       - '{"enabled" = 0;"name" = "MOVIES";}'
#       - '{"enabled" = 0;"name" = "PRESENTATIONS";}'
#       - '{"enabled" = 0;"name" = "SPREADSHEETS";}'
#       - '{"enabled" = 0;"name" = "SOURCE";}'
#       - '{"enabled" = 0;"name" = "MENU_DEFINITION";}'
#       - '{"enabled" = 0;"name" = "MENU_OTHER";}'
#       - '{"enabled" = 0;"name" = "MENU_CONVERSION";}'
#       - '{"enabled" = 0;"name" = "MENU_EXPRESSION";}'
#       - '{"enabled" = 0;"name" = "MENU_WEBSEARCH";}'
#       - '{"enabled" = 0;"name" = "MENU_SPOTLIGHT_SUGGESTIONS";}'

# - name: Disable spotlight indexing on new volumes
#   osx_defaults:
#     state: present
#     domain: /.Spotlight-V100/VolumeConfiguration
#     key: Exclusions
#     type: array
#     value:
#       - /Volumes
#   become: true
#   become_user: root
#   tags:
#     - sudo

# - name: Hide spotlight menu bar icon
#   file:
#     path: /System/Library/CoreServices/Search.bundle/Contents/MacOS/Search
#     mode: 0600
#   become: true
#   become_user: root
#   tags:
#     - sudo