- name: Use plain text mode for new TextEdit documents
  osx_defaults:
    state: present
    domain: com.apple.TextEdit
    key: RichText
    type: int
    value: 0

- name: Open files as UTF-8 in TextEdit
  osx_defaults:
    state: present
    domain: com.apple.TextEdit
    key: PlainTextEncoding
    type: int
    value: 4

- name: Save files as UTF-8 in TextEdit
  osx_defaults:
    state: present
    domain: com.apple.TextEdit
    key: PlainTextEncodingForWrite
    type: int
    value: 4
