- name: Get our digital ocean api token
  set_fact:
    do_api_token: "{{
      lookup(
        'onepassword_raw',
        'Digital Ocean'
      ) | json_query('details.sections[?title==`PERSONAL ACCESS TOKENS`].fields | [] | [?t==`local`].v | [0]')
    }}"
  no_log: true
  tags:
    - post
    - onepassword

- name: Create the digital ocean config directory
  file:
    state: directory
    path: "{{ ansible_env.HOME }}/Library/ApplicationSupport/doctl"
    mode: 0755
    owner: "{{ ansible_user_id }}"
  register: R_doctl_dir

- name: Template the digital ocean config file
  template:
    src: config.yaml.j2
    dest: "{{ R_doctl_dir.path }}/config.yaml"
    mode: 0600
    owner: "{{ ansible_user_id }}"
  tags:
    - post
    - onepassword
