- name: Make sure zsh directory exists
  file:
    state: directory
    dest: "{{ role_path }}/zsh"
    mode: 0700
    owner: "{{ ansible_user_id }}"

- name: Template config.zsh into zsh/config.zsh
  template:
    src: config.zsh.j2
    dest: "{{ role_path }}/zsh/config.zsh"
    mode: 0600
    owner: "{{ ansible_user_id }}"
