- name: Write the global git config file
  template:
    src: gitconfig_global.j2
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    mode: 0600
    owner: "{{ ansible_user_id }}"

- name: Write the global gitignore file
  copy:
    src: gitignore_global
    dest: "{{ ansible_env.HOME }}/.gitignore"
    mode: 0600
    owner: "{{ ansible_user_id }}"

- name: Write the gitconfig users files
  template:
    src: gitconfig_user_local.j2
    dest: "{{ ansible_env.HOME }}/.gitconfig-{{ item.value.shorthand }}.local"
    mode: 0600
    owner: "{{ ansible_user_id }}"
  loop: "{{ git_users | dict2items }}"
