- name: Run brew update
  command: brew update
  register: R_brew_update
  changed_when:
    - R_brew_update.stderr

- name: Write brewfile to home directory
  template:
    src: Brewfile.j2
    dest: "{{ ansible_env.HOME }}/.Brewfile"
    mode: 0600
    owner: "{{ ansible_user_id }}"

- name: Install homebrew packages with bundle
  command: brew bundle --global
  register: R_brew_bundle
  changed_when:
    - (R_brew_bundle.stderr)                 or
      ("Installing" in R_brew_bundle.stdout) or
      ("Upgrading"  in R_brew_bundle.stdout)
  tags:
    - internet

- name: Output bundle
  debug:
    msg: "{{ R_brew_bundle.stdout_lines }}"
  when:
    - R_brew_bundle.changed
  tags:
    - internet

- name: Cleanup homebrew with bundle
  command: brew bundle cleanup --global --force
  register: R_brew_bundle_clean
  changed_when:
    - R_brew_bundle_clean.stdout or R_brew_bundle_clean.stderr
  tags:
    - internet

- name: Output bundle cleanup
  debug:
    msg: "{{ R_brew_bundle_clean.stdout_lines }}"
  when:
    - R_brew_bundle_clean.changed

# Brewfile only upgrades direct packagers. We run this in case
# dependencies or brew itself need upgrades.
- name: Run brew upgrade
  command: brew upgrade
  register: R_brew_upgrade
  changed_when:
    - R_brew_upgrade.stdout or R_brew_upgrade.stderr

- name: Output brew upgrade
  debug:
    msg: "{{ R_brew_upgrade.stdout_lines }}\n{{ R_brew_upgrade.stderr_lines }}"
  when:
    - R_brew_upgrade.changed

- name: Run brew cleanup
  command: brew cleanup
  register: R_brew_cleanup
  changed_when:
    - R_brew_cleanup.stderr or R_brew_cleanup.stdout

- name: Output brew cleanup
  debug:
    msg: "{{ R_brew_cleanup.stdout_lines }}\n{{ R_brew_cleanup.stderr_lines }}"
  when:
    - R_brew_cleanup.changed
