- name: Make sure zsh directory exists
  file:
    state: directory
    dest: "{{ role_path }}/zsh"
    mode: 0700
    owner: "{{ ansible_user_id }}"

- name: Template path.zsh into zsh/path.zsh
  template:
    src: path.zsh.j2
    dest: "{{ role_path }}/zsh/path.zsh"
    mode: 0600
    owner: "{{ ansible_user_id }}"

- name: Template out dot into bin/dot
  template:
    src: dot.j2
    dest: "{{ role_path }}/bin/dot"
    mode: 0700
    owner: "{{ ansible_user_id }}"

- name: Make sure everything in bin is 0700
  file:
    path: "{{ role_path }}/bin/"
    recurse: true
    mode: 0700
    owner: "{{ ansible_user_id }}"
