- name: Make sure zsh directory exists
  file:
    state: directory
    dest: "{{ role_path }}/zsh"
    mode: 0700
    owner: "{{ ansible_user_id }}"

- name: Template path.zsh into zsh/path.zsh
  template:
    src: path.zsh.j2
    dest: "{{ role_path }}/zsh/path.zsh"
    mode: 0600
    owner: "{{ ansible_user_id }}"

- name: Install all go packages
  command: go get -u {{ item }}
  environment:
    GOPATH: "{{ gopath | expanduser }}"
    GO111MODULE: on
  loop: "{{ go_gets }}"
  register: R_goget
  changed_when:
    - R_goget.stdout or R_goget.stderr
  tags:
    - internet
