#!/usr/bin/env bash
#
# Run all dotfiles installers.
set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
echo "Enforcing Brewfile"
brew bundle
brew bundle cleanup --force
brew upgrade
brew cleanup
brew prune
brew doctor

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
