- name: Enable nextdns
  block:
    - name: Check if nextdns is running
      command: nextdns status
      become: true
      become_user: root
      register: R_nextdns_status
      changed_when:
        - R_nextdns_status.stdout != "running"
      failed_when:
        - R_nextdns_status.rc != 0

    - name: Enable nextdns
      command: nextdns install -config {{ nextdns_config }} -report-client-info -auto-activate
      become: true
      become_user: root
      when:
        - R_nextdns_status.stdout != "running"
  tags:
    - sudo
