- name: Write sublime settings
  copy:
    src: settings.json
    dest: "{{ ansible_env.HOME }}/Library/Application Support/Sublime Text/Packages/User/Preferences.sublime-settings"
    mode: 0600
    owner: "{{ ansible_user_id }}"
  tags:
    - post

- name: Write sublime keybindings
  copy:
    src: keybindings.json
    dest: "{{ ansible_env.HOME }}/Library/Application Support/Sublime Text/Packages/User/Default (OSX).sublime-keymap"
    mode: 0600
    owner: "{{ ansible_user_id }}"
  tags:
    - post
