- name: Make sure the file exists first
  stat:
    path: "{{ sublime_settings_file_location | expanduser }}"
  register: R_sublime_settings_stat

- name: Create a temporary file if one does not exist
  file:
    path: "{{ sublime_settings_file_location | expanduser }}"
    state: touch
    mode: 0600
    owner: "{{ ansible_user_id }}"
  when:
    - not R_sublime_settings_stat.stat.exists

- name: Symlink the sublime global settings
  file:
    src: "{{ role_path }}/symlinks/settings.json"
    dest: "{{ sublime_settings_file_location | expanduser }}"
    state: link
    force: true
    mode: 0600
    owner: "{{ ansible_user_id }}"
