- name: Make the docker directory
  file:
    state: directory
    path: "{{ ansible_env.HOME }}/.docker"
    mode: 0700
    owner: "{{ ansible_user_id }}"
  register: R_docker_dir

- name: Write docker daemon file
  copy:
    src: daemon.json
    dest: "{{ R_docker_dir.path }}/daemon.json"
    mode: 0600
    owner: "{{ ansible_user_id }}"

- name: Write the default hadolint file
  copy:
    src: hadolint.yaml
    dest: "{{ ansible_env.HOME }}/.config/hadolint.yaml"
    mode: 0600
    owner: "{{ ansible_user_id }}"
