- name: Make sure the config directory exists
  file:
    state: directory
    dest: "{{ ansible_env.HOME }}/.config"
    mode: 0700
    owner: "{{ ansible_user_id }}"

- name: Write the starship config file
  copy:
    src: starship.toml
    dest: "{{ ansible_env.HOME }}/.config/starship.toml"
    mode: 0600
    owner: "{{ ansible_user_id }}"
