- name: Create a dictionary of netrc machines to their usernames and passwords
  set_fact:
    netrc_machines_to_logins: "{{ netrc_machines_to_logins | default({}) | combine(
      {item.value.machine: {
        'login': item.value.login,
        'password': lookup(
          'onepassword_raw',
          item.value.op_name,
          subdomain=op_auths[item.value.op_shorthand].shorthand,
          username=op_auths[item.value.op_shorthand].email,
          secret_key=op_auths[item.value.op_shorthand].secret_key,
          vault_password=lookup('vars', 'op_password_'+op_auths[item.value.op_shorthand].shorthand)
        ) | json_query('details.sections[?title==`' + item.value.op_section_title + '`].fields | [] | [?t==`' + item.value.op_label + '`].v | [0]') }
      }
    ) }}"
  loop: "{{ netrc_logins | dict2items }}"
  tags:
    - post
    - 1password

- name: Write the netrc file
  template:
    src: netrc.j2
    dest: "{{ ansible_env.HOME }}/.netrc"
    mode: 0600
    owner: "{{ ansible_user_id }}"
  tags:
    - post
    - 1password
