- name: Create a dictionary of netrc machines to their usernames and passwords
  set_fact:
    netrc_machines_to_logins: "{{ netrc_machines_to_logins | default({}) | combine(
      {item.value.machine: {
        'login': item.value.login,
        'password': lookup(
          'onepassword_raw',
          item.value.op_name
        ) | json_query('details.sections[?title==`' + item.value.op_section_title + '`].fields | [] | [?t==`' + item.value.op_label + '`].v | [0]') }
      }
    ) }}"
  loop: "{{ netrc_logins | dict2items }}"
  no_log: true
  tags:
    - post
    - onepassword

- name: Write the netrc file
  template:
    src: netrc.j2
    dest: "{{ ansible_env.HOME }}/.netrc"
    mode: 0600
    owner: "{{ ansible_user_id }}"
  no_log: true
  tags:
    - post
    - onepassword
