- name: Create the 1password CLI directory
  file:
    state: directory
    dest: "{{ ansible_env.HOME }}/.op"
    mode: 0700
    owner: "{{ ansible_user_id }}"

- name: Copy over the 1password CLI config
  template:
    src: op_config.json
    dest: "{{ ansible_env.HOME }}/.op/config"
    mode: 0600
    owner: "{{ ansible_user_id }}"

- name: Check if there's a 1password cli update
  shell: /usr/local/bin/op update
  register: R_op_update
  changed_when:
    - ("Please download our latest version" in R_op_update.stdout)
  tags:
    - post
    - internet
    - 1password

- name: Update 1password CLI
  command: brew cask reinstall 1password-cli
  when:
    - ("Please download our latest version" in R_op_update.stdout)
  tags:
    - post
    - internet
    - 1password

# Don't want to mark this as "changed" if it's a successful login
# https://github.com/ansible/ansible/blob/stable-2.6/changelogs/CHANGELOG-v2.6.rst
- name: Auth to 1password CLI
  shell: echo "{{ op_password }}" | /usr/local/bin/op signin {{ op_domain }} {{ op_email }} {{ op_secret_key }} --output=raw
  no_log: true
  register: R_op_signin
  changed_when:
    - R_op_signin.rc != 0
  tags:
    - post
    - internet
    - 1password
