name: Validate

on:
  - push

jobs:
  validate:
    runs-on: ubuntu-latest
    container: lingrino/ci:latest
    steps:
      - name: Code - Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Ansible Lint
        run: ansible-lint main.yml
