- name: Make sure the config directory exists
  file:
    state: directory
    dest: "{{ ansible_env.HOME }}/.config"
    mode: 0700
    owner: "{{ ansible_user_id }}"

- name: Make sure the bat config directory exists
  file:
    state: directory
    dest: "{{ ansible_env.HOME }}/.config/bat"
    mode: 0700
    owner: "{{ ansible_user_id }}"

- name: Write the bat config file
  copy:
    src: config
    dest: "{{ ansible_env.HOME }}/.config/bat/config"
    mode: 0600
    owner: "{{ ansible_user_id }}"
